import * as vscode from "vscode";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import * as https from "https";
import * as http from "http";
import { URL } from "url";

// ─── Status Bar ───────────────────────────────────────────────────────────────
let statusBarItem: vscode.StatusBarItem;

function updateStatusBar(enabled: boolean) {
  statusBarItem.text = enabled ? "$(globe) PT→EN: ON" : "$(globe) PT→EN: OFF";
  statusBarItem.tooltip = enabled
    ? "claudept2en is active. Click to disable."
    : "claudept2en is inactive. Click to enable.";
  statusBarItem.command = enabled
    ? "claudePt2En.disable"
    : "claudePt2En.enable";
  statusBarItem.backgroundColor = enabled
    ? new vscode.ThemeColor("statusBarItem.warningBackground")
    : undefined;
}

// ─── LibreTranslate ───────────────────────────────────────────────────────────
async function translateToEnglish(text: string): Promise<string> {
  const config = vscode.workspace.getConfiguration("claudePt2En");
  const baseUrl = config.get<string>("libreTranslateUrl") || "https://libretranslate.com";
  const apiKey  = config.get<string>("libreTranslateApiKey") || "";

  const body = JSON.stringify({
    q:      text,
    source: "pt",
    target: "en",
    format: "text",
    ...(apiKey ? { api_key: apiKey } : {}),
  });

  return new Promise((resolve, reject) => {
    const endpoint = new URL("/translate", baseUrl);
    const lib      = endpoint.protocol === "https:" ? https : http;

    const req = lib.request(
      {
        hostname: endpoint.hostname,
        port:     endpoint.port || (endpoint.protocol === "https:" ? 443 : 80),
        path:     endpoint.pathname,
        method:   "POST",
        headers:  { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(body) },
      },
      (res) => {
        let data = "";
        res.on("data", (chunk) => (data += chunk));
        res.on("end", () => {
          try {
            const json = JSON.parse(data);
            if (json.translatedText) {
              resolve(json.translatedText);
            } else if (json.error) {
              reject(new Error(json.error));
            } else {
              reject(new Error("Unexpected response: " + data));
            }
          } catch {
            reject(new Error("Failed to parse response: " + data));
          }
        });
      }
    );

    req.on("error", reject);
    req.write(body);
    req.end();
  });
}

// ─── Language detection (heuristic – avoids calling API for already-English) ─
function looksLikePortuguese(text: string): boolean {
  if (text.trim().length < 3) { return false; }

  const ptMarkers = [
    // common PT words
    /\b(o|a|os|as|um|uma|uns|umas)\b/i,
    /\b(de|do|da|dos|das|em|no|na|nos|nas|ao|aos|à|às)\b/i,
    /\b(e|ou|mas|porém|portanto|então|porque|que|se|como)\b/i,
    /\b(eu|você|ele|ela|nós|eles|elas|meu|minha|seu|sua)\b/i,
    /\b(é|está|são|estão|tem|têm|vai|vão|foi|foram)\b/i,
    /\b(para|com|por|sobre|entre|até|após|antes)\b/i,
    /\b(fazer|criar|adicionar|remover|alterar|verificar|mostrar|listar)\b/i,
    // accented characters common in Portuguese
    /[çã]/,
    /[ãõ]/,
    /[áéíóúâêîôû]/,
  ];

  const matches = ptMarkers.filter((re) => re.test(text)).length;
  return matches >= 2;
}

// ─── Wrapper script (PTY-based input interceptor) ─────────────────────────────
function getWrapperScriptPath(): string {
  return path.join(os.homedir(), ".vscode-claude-pt-wrapper.sh");
}

function generateWrapperScript(libreTranslateUrl: string, apiKey: string): string {
  return `#!/usr/bin/env bash
# Auto-generated by claudept2en extension
# Wraps Claude Code to translate PT input → EN before sending

LIBRETRANSLATE_URL="${libreTranslateUrl}"
LIBRETRANSLATE_KEY="${apiKey}"

translate_text() {
  local text="$1"
  local payload

  if [ -n "$LIBRETRANSLATE_KEY" ]; then
    payload=$(printf '{"q":"%s","source":"pt","target":"en","format":"text","api_key":"%s"}' \
      "$(echo "$text" | sed 's/"/\\\\"/g')" "$LIBRETRANSLATE_KEY")
  else
    payload=$(printf '{"q":"%s","source":"pt","target":"en","format":"text"}' \
      "$(echo "$text" | sed 's/"/\\\\"/g')")
  fi

  local result
  result=$(curl -s -X POST "$LIBRETRANSLATE_URL/translate" \\
    -H "Content-Type: application/json" \\
    -d "$payload" 2>/dev/null)

  echo "$result" | grep -o '"translatedText":"[^"]*"' | sed 's/"translatedText":"//;s/"$//'
}

looks_like_portuguese() {
  local text="$1"
  echo "$text" | grep -qiP '\\b(o|a|de|do|da|em|para|com|que|se|é|está|são|você|fazer|criar)\\b' && return 0
  echo "$text" | grep -qP '[ãõção]' && return 0
  return 1
}

# Use readline wrapper for interactive input interception
if command -v rlwrap &>/dev/null; then
  exec rlwrap -p -a -e '' bash -c '
    while IFS= read -r -e -p "" line; do
      history -s "$line"
      echo
      if looks_like_portuguese "$line" 2>/dev/null; then
        translated=$(translate_text "$line")
        [ -n "$translated" ] && line="$translated"
      fi
      echo "$line"
    done
  '
else
  # Fallback: pure bash readline loop piped to claude
  (
    while IFS= read -r -e line; do
      history -s "$line"
      if looks_like_portuguese "$line" 2>/dev/null; then
        translated=$(translate_text "$line")
        [ -n "$translated" ] && line="$translated"
      fi
      printf '%s\\n' "$line"
    done
  ) | claude "$@"
fi
`;
}

// ─── Setup: install wrapper ────────────────────────────────────────────────────
async function setupWrapper(context: vscode.ExtensionContext) {
  const config  = vscode.workspace.getConfiguration("claudePt2En");
  const url     = config.get<string>("libreTranslateUrl") || "https://libretranslate.com";
  const apiKey  = config.get<string>("libreTranslateApiKey") || "";
  const script  = generateWrapperScript(url, apiKey);
  const outPath = getWrapperScriptPath();

  fs.writeFileSync(outPath, script, { mode: 0o755 });
  await config.update("wrapperScriptPath", outPath, vscode.ConfigurationTarget.Global);
  return outPath;
}

// ─── Terminal-based PT→EN (intercepts typed text via sendText override) ───────
// This is the primary mechanism: we create a pseudo-terminal that:
//   1. Renders output from the real Claude Code process
//   2. Intercepts Enter keystrokes, translates if PT, then forwards to Claude
function createTranslatingTerminal(context: vscode.ExtensionContext): vscode.Terminal {
  const config   = vscode.workspace.getConfiguration("claudePt2En");
  const enabled  = config.get<boolean>("enabled") ?? true;
  const showNote = config.get<boolean>("showNotification") ?? true;

  let inputBuffer = "";

  const pty: vscode.Pseudoterminal = {
    onDidWrite: new vscode.EventEmitter<string>().event,
    open() {},
    close() {},
    handleInput: async (data: string) => {
      // data is the raw keystroke sequence
      if (data === "\r" || data === "\n") {
        // Enter pressed – decide whether to translate
        const trimmed = inputBuffer.trim();
        inputBuffer   = "";

        if (enabled && trimmed && looksLikePortuguese(trimmed)) {
          try {
            const translated = await translateToEnglish(trimmed);
            if (showNote) {
              vscode.window.showInformationMessage(
                `PT→EN: "${trimmed.slice(0, 60)}${trimmed.length > 60 ? "…" : ""}" → "${translated.slice(0, 60)}${translated.length > 60 ? "…" : ""}"`
              );
            }
            // The active terminal forwards the translated text
            vscode.window.activeTerminal?.sendText(translated, true);
          } catch (err: any) {
            vscode.window.showWarningMessage(`PT→EN translation failed: ${err.message}. Sending original.`);
            vscode.window.activeTerminal?.sendText(trimmed, true);
          }
        } else {
          vscode.window.activeTerminal?.sendText(trimmed, true);
        }
      } else if (data === "\x7f") {
        // Backspace
        inputBuffer = inputBuffer.slice(0, -1);
      } else if (data.charCodeAt(0) >= 32) {
        inputBuffer += data;
      }
    },
  };

  return vscode.window.createTerminal({ name: "PT→EN Interceptor", pty });
}

// ─── sendText monkey-patch approach (simpler, works with existing terminals) ──
// We override the workspace terminal profile to inject the wrapper script.
function injectTranslationIntoShellProfile(context: vscode.ExtensionContext, scriptPath: string) {
  const vsConfig = vscode.workspace.getConfiguration();

  // Add a terminal profile that runs the PT→EN wrapper
  const profiles = vsConfig.get<Record<string, unknown>>("terminal.integrated.profiles.linux") || {};
  (profiles as any)["claudept2en"] = {
    path:  "bash",
    args:  ["--rcfile", scriptPath],
    icon:  "globe",
  };

  vsConfig.update(
    "terminal.integrated.profiles.linux",
    profiles,
    vscode.ConfigurationTarget.Global
  );

  // macOS
  const macProfiles = vsConfig.get<Record<string, unknown>>("terminal.integrated.profiles.osx") || {};
  (macProfiles as any)["claudept2en"] = {
    path:  "bash",
    args:  ["--rcfile", scriptPath],
    icon:  "globe",
  };
  vsConfig.update(
    "terminal.integrated.profiles.osx",
    macProfiles,
    vscode.ConfigurationTarget.Global
  );
}

// ─── Real-time sendText interceptor ──────────────────────────────────────────
// Patches vscode.window.createTerminal to wrap sendText on every new terminal.
function patchTerminalSendText(context: vscode.ExtensionContext) {
  const config   = vscode.workspace.getConfiguration("claudePt2En");
  const showNote = config.get<boolean>("showNotification") ?? true;

  const originalCreate = vscode.window.createTerminal.bind(vscode.window);

  // We intercept every terminal open and wrap sendText
  context.subscriptions.push(
    vscode.window.onDidOpenTerminal((terminal) => {
      const enabled = vscode.workspace
        .getConfiguration("claudePt2En")
        .get<boolean>("enabled") ?? true;

      if (!enabled) { return; }

      // Wrap sendText
      const originalSend = terminal.sendText.bind(terminal);
      (terminal as any).sendText = async (text: string, addNewLine?: boolean) => {
        const trimmed = text.trim();
        if (trimmed && looksLikePortuguese(trimmed)) {
          try {
            const translated = await translateToEnglish(trimmed);
            if (showNote) {
              vscode.window.showInformationMessage(
                `🌐 PT→EN: "${trimmed.slice(0, 50)}…" → "${translated.slice(0, 50)}…"`
              );
            }
            originalSend(translated, addNewLine);
            return;
          } catch (err: any) {
            vscode.window.showWarningMessage(`PT→EN failed: ${err.message}`);
          }
        }
        originalSend(text, addNewLine);
      };
    })
  );
}

// ─── Shell integration hook (best approach for Claude Code) ──────────────────
// Generates a bash function that wraps the `claude` binary and translates stdin.
function generateBashFunction(libreTranslateUrl: string, apiKey: string): string {
  const keyParam = apiKey ? `, "api_key": "${apiKey}"` : "";
  return `
# ── claudept2en (auto-injected by VSCode extension) ──
__claude_pt_translate() {
  local text="$1"
  local url="${libreTranslateUrl}/translate"
  local payload="{\"q\": $(echo "$text" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read().strip()))'), \"source\": \"pt\", \"target\": \"en\", \"format\": \"text\"${keyParam}}"
  curl -sf -X POST "$url" -H 'Content-Type: application/json' -d "$payload" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("translatedText",""))' 2>/dev/null
}

__claude_pt_looks_portuguese() {
  echo "$1" | grep -qiP '(\\b(o|a|de|do|da|em|para|que|se|é|você|fazer|criar|adicionar|remover|verificar|mostrar|listar)\\b|[ãõção])' 
}

claude() {
  if [ -t 0 ] && [ $# -eq 0 ]; then
    # Interactive mode: wrap readline
    local TMPFILE
    TMPFILE=$(mktemp /tmp/claude_input.XXXXXX)
    while IFS= read -r -e -p $'\\001\\033[1;36m\\002claude❯ \\001\\033[0m\\002' line; do
      history -s "$line"
      if __claude_pt_looks_portuguese "$line"; then
        local translated
        translated=$(__claude_pt_translate "$line")
        if [ -n "$translated" ]; then
          echo -e "  \\033[2m[PT→EN] $translated\\033[0m" >&2
          line="$translated"
        fi
      fi
      printf '%s\\n' "$line" >> "$TMPFILE"
    done
    command claude < "$TMPFILE"
    rm -f "$TMPFILE"
  else
    command claude "$@"
  fi
}
export -f claude 2>/dev/null || true
# ── end claudept2en ──
`;
}

function getBashRcPath(): string {
  return path.join(os.homedir(), ".bashrc");
}

function getZshRcPath(): string {
  return path.join(os.homedir(), ".zshrc");
}

const MARKER_START = "# ── claudept2en (auto-injected by VSCode extension) ──";
const MARKER_END   = "# ── end claudept2en ──";

function injectIntoBashRc(content: string, rcPath: string) {
  let existing = "";
  try { existing = fs.readFileSync(rcPath, "utf8"); } catch { /* new file */ }

  // Remove old injection if present
  const startIdx = existing.indexOf(MARKER_START);
  const endIdx   = existing.indexOf(MARKER_END);
  if (startIdx !== -1 && endIdx !== -1) {
    existing = existing.slice(0, startIdx) + existing.slice(endIdx + MARKER_END.length + 1);
  }

  fs.writeFileSync(rcPath, existing.trimEnd() + "\n\n" + content + "\n", "utf8");
}

function removeFromBashRc(rcPath: string) {
  try {
    let existing = fs.readFileSync(rcPath, "utf8");
    const startIdx = existing.indexOf(MARKER_START);
    const endIdx   = existing.indexOf(MARKER_END);
    if (startIdx !== -1 && endIdx !== -1) {
      existing = existing.slice(0, startIdx) + existing.slice(endIdx + MARKER_END.length + 1);
      fs.writeFileSync(rcPath, existing, "utf8");
    }
  } catch { /* ignore */ }
}

// ─── Activate ─────────────────────────────────────────────────────────────────
export async function activate(context: vscode.ExtensionContext) {
  // Status bar
  statusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right, 100);
  context.subscriptions.push(statusBarItem);

  const config  = vscode.workspace.getConfiguration("claudePt2En");
  const enabled = config.get<boolean>("enabled") ?? true;
  updateStatusBar(enabled);
  statusBarItem.show();

  // Inject bash function into shell rc files
  async function doInject() {
    const cfg    = vscode.workspace.getConfiguration("claudePt2En");
    const url    = cfg.get<string>("libreTranslateUrl") || "https://libretranslate.com";
    const apiKey = cfg.get<string>("libreTranslateApiKey") || "";
    const fn     = generateBashFunction(url, apiKey);

    injectIntoBashRc(fn, getBashRcPath());
    // Also inject in .zshrc if it exists
    if (fs.existsSync(getZshRcPath())) {
      injectIntoBashRc(fn, getZshRcPath());
    }
  }

  if (enabled) { await doInject(); }

  // ── Commands ──────────────────────────────────────────────────────────────
  context.subscriptions.push(
    vscode.commands.registerCommand("claudePt2En.enable", async () => {
      await vscode.workspace
        .getConfiguration("claudePt2En")
        .update("enabled", true, vscode.ConfigurationTarget.Global);
      updateStatusBar(true);
      await doInject();
      vscode.window.showInformationMessage(
        "✅ claudept2en enabled. Open a new terminal for changes to take effect."
      );
    })
  );

  context.subscriptions.push(
    vscode.commands.registerCommand("claudePt2En.disable", async () => {
      await vscode.workspace
        .getConfiguration("claudePt2En")
        .update("enabled", false, vscode.ConfigurationTarget.Global);
      updateStatusBar(false);
      removeFromBashRc(getBashRcPath());
      removeFromBashRc(getZshRcPath());
      vscode.window.showInformationMessage(
        "⛔ claudept2en disabled."
      );
    })
  );

  context.subscriptions.push(
    vscode.commands.registerCommand("claudePt2En.setLibreTranslateUrl", async () => {
      const current = config.get<string>("libreTranslateUrl") || "https://libretranslate.com";
      const input   = await vscode.window.showInputBox({
        prompt:      "Enter LibreTranslate server URL",
        value:       current,
        placeHolder: "http://localhost:5000  or  https://libretranslate.com",
      });
      if (input) {
        await vscode.workspace
          .getConfiguration("claudePt2En")
          .update("libreTranslateUrl", input.trim(), vscode.ConfigurationTarget.Global);
        await doInject();
        vscode.window.showInformationMessage(`LibreTranslate URL set to: ${input.trim()}`);
      }
    })
  );

  context.subscriptions.push(
    vscode.commands.registerCommand("claudePt2En.translateSelection", async () => {
      const editor = vscode.window.activeTextEditor;
      if (!editor) { return; }
      const selection = editor.selection;
      const text      = editor.document.getText(selection);
      if (!text.trim()) {
        vscode.window.showWarningMessage("No text selected.");
        return;
      }
      try {
        const translated = await translateToEnglish(text);
        editor.edit((eb) => eb.replace(selection, translated));
        vscode.window.showInformationMessage(`Translated: "${translated.slice(0, 80)}"`);
      } catch (err: any) {
        vscode.window.showErrorMessage(`Translation failed: ${err.message}`);
      }
    })
  );

  // Re-inject whenever config changes (URL or key updated)
  context.subscriptions.push(
    vscode.workspace.onDidChangeConfiguration(async (e) => {
      if (e.affectsConfiguration("claudePt2En")) {
        const cfg = vscode.workspace.getConfiguration("claudePt2En");
        updateStatusBar(cfg.get<boolean>("enabled") ?? true);
        if (cfg.get<boolean>("enabled")) { await doInject(); }
      }
    })
  );

  vscode.window.showInformationMessage(
    "🌐 claudept2en active! Open a new terminal and run `claude` to use."
  );
}

export function deactivate() {
  removeFromBashRc(getBashRcPath());
  removeFromBashRc(getZshRcPath());
}
